<?php
use Migrations\AbstractSeed;

/**
 * CakeCmsArticles seed.
 */
class CakeCmsArticlesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '15',
                'user_id' => '6',
                'title' => 'First Post',
                'slug' => 'yue-yao-ri',
                'body' => 'This is the fierst post.',
                'published' => '0',
                'created' => '2021-02-22 02:38:35',
                'modified' => '2022-04-24 03:30:21',
            ],
            [
                'id' => '18',
                'user_id' => '7',
                'title' => 'fumiko\'s post',
                'slug' => 'fu-mei-zino-tou-gao',
                'body' => '富美子です!!みんな元気にしてますか？？暑さに負けないでね！！',
                'published' => '0',
                'created' => '2021-02-22 03:08:30',
                'modified' => '2022-08-14 03:46:56',
            ],
            [
                'id' => '19',
                'user_id' => '8',
                'title' => '啓斗の投稿',
                'slug' => 'qi-douno-tou-gao',
                'body' => '啓斗です keito',
                'published' => '0',
                'created' => '2021-02-22 03:12:23',
                'modified' => '2022-04-23 09:14:34',
            ],
            [
                'id' => '20',
                'user_id' => '9',
                'title' => '誠一の投稿',
                'slug' => 'cheng-yino-tou-gao',
                'body' => '誠一です seiichi',
                'published' => '0',
                'created' => '2021-02-22 03:14:41',
                'modified' => '2021-03-13 05:22:06',
            ],
            [
                'id' => '39',
                'user_id' => '5',
                'title' => 'Time Zone の設定を変更',
                'slug' => 'Time-Zone-no-she-dingwo-bian-gengshimashita',
                'body' => 'UTCー＞Asia/Tokyo/Nagoya  <--error happend !!

',
                'published' => '0',
                'created' => '2021-03-14 00:12:25',
                'modified' => '2022-07-30 08:08:14',
            ],
            [
                'id' => '40',
                'user_id' => '5',
                'title' => 'tom : 時刻の確認-1',
                'slug' => 'tom-shi-keno-que-ren',
                'body' => 'now : 0:17
8/21-11:20 add tagstring test bare
authoraizetion test',
                'published' => '0',
                'created' => '2021-03-14 00:16:02',
                'modified' => '2022-07-24 05:06:27',
            ],
            [
                'id' => '41',
                'user_id' => '5',
                'title' => 'login test',
                'slug' => 'login-test',
                'body' => 'login test、8/21-11:20 add tags test,bare、今日はなんの日？',
                'published' => '0',
                'created' => '2021-05-28 17:15:25',
                'modified' => '2022-08-14 10:36:43',
            ],
            [
                'id' => '43',
                'user_id' => '5',
                'title' => 'もうすぐワクチンの接種が受けられます',
                'slug' => 'mousuguwakuchinno-jie-zhongga-shoukeraremasu',
                'body' => '６月１１日金曜日、10:00AM、白山リハビリテーション病院の予約完了
４回目完了しました！',
                'published' => '0',
                'created' => '2021-06-08 15:48:50',
                'modified' => '2022-08-02 06:42:39',
            ],
            [
                'id' => '46',
                'user_id' => '5',
                'title' => 'オリンピックはどうなるのでしょうか？',
                'slug' => 'orinpikkuhadounarunodeshouka',
                'body' => '中止になったら、選手がかわいそうだし！　かと言って、今の状態ではコロナの再拡大につながりそうだし！
悩ましいところです',
                'published' => '0',
                'created' => '2021-06-08 15:59:14',
                'modified' => '2022-07-24 05:23:02',
            ],
            [
                'id' => '47',
                'user_id' => '5',
                'title' => 'CMS　Turtorial の見直し',
                'slug' => 'CMS-Turtorial-no-jian-zhishi',
                'body' => '途中でやめていた、機能追加を再開します
動かん！わからん！',
                'published' => '0',
                'created' => '2021-06-13 14:17:29',
                'modified' => '2022-07-24 05:37:19',
            ],
            [
                'id' => '48',
                'user_id' => '5',
                'title' => 'Articles->patchEntity',
                'slug' => 'Articles-patchEntity',
                'body' => 'confirm data
check edit action',
                'published' => '0',
                'created' => '2021-06-13 16:30:29',
                'modified' => '2022-07-24 05:43:09',
            ],
            [
                'id' => '49',
                'user_id' => '5',
                'title' => '自分以外の投稿者の記事の編集テスト',
                'slug' => 'add-test',
                'body' => '他人の投稿記事の編集が出来てしまいました、問題ですね、修正しましょう、Userの欄が選択オプションになっています、固定表示に変えましょう',
                'published' => '0',
                'created' => '2021-06-13 16:36:42',
                'modified' => '2022-08-15 05:12:11',
            ],
            [
                'id' => '56',
                'user_id' => '5',
                'title' => 'バリデーションのテストです',
                'slug' => 'validate-test',
                'body' => 'CakePHPのバリデーションは強力です',
                'published' => '0',
                'created' => '2021-06-13 17:32:16',
                'modified' => '2022-08-15 05:02:23',
            ],
            [
                'id' => '59',
                'user_id' => '5',
                'title' => 'query builder',
                'slug' => 'query-builder',
                'body' => 'query builder',
                'published' => '0',
                'created' => '2021-06-15 14:04:50',
                'modified' => '2021-06-25 15:37:34',
            ],
            [
                'id' => '82',
                'user_id' => '5',
                'title' => 'CakePHP学習再開',
                'slug' => 'CakePHP-xue-xi-zai-kai',
                'body' => '6か月のブランクでした、昨日から再開しました',
                'published' => '0',
                'created' => '2022-03-23 11:32:37',
                'modified' => '2022-03-23 11:32:37',
            ],
            [
                'id' => '83',
                'user_id' => '5',
                'title' => 'テーブルのリレーション',
                'slug' => 'teburunorireshon',
                'body' => 'belongsToMany（多対多）のおさらいです。articlesTable と tagsTableの関連を定義して必要な機能を実装していきます。',
                'published' => '0',
                'created' => '2022-04-19 11:36:00',
                'modified' => '2022-04-21 03:13:14',
            ],
            [
                'id' => '84',
                'user_id' => '5',
                'title' => 'オミクロン下火に！',
                'slug' => 'yai-yan-te',
                'body' => 'オミクロン株の流行が減少傾向になってきました。GWに向けて人出が増えるとまた盛り返しそうで、少々心配です。',
                'published' => '0',
                'created' => '2022-04-21 06:43:55',
                'modified' => '2022-04-21 06:43:55',
            ],
            [
                'id' => '85',
                'user_id' => '5',
                'title' => 'シンプルなスラグ生成の追加',
                'slug' => 'ay-ya-ya-ya-ya',
                'body' => 'テーブルの　beforeSave　メソッドにスラグ作成機能を作る',
                'published' => '0',
                'created' => '2022-04-21 07:06:47',
                'modified' => '2022-04-22 03:12:58',
            ],
            [
                'id' => '92',
                'user_id' => '5',
                'title' => 'cake3102 test',
                'slug' => 'cake3102-test',
                'body' => '計算フィールドの追加',
                'published' => '0',
                'created' => '2022-04-22 06:03:42',
                'modified' => '2022-04-22 06:03:42',
            ],
            [
                'id' => '93',
                'user_id' => '5',
                'title' => 'タグのテスト',
                'slug' => 'tagunotesuto',
                'body' => 'タグが付かない？',
                'published' => '0',
                'created' => '2022-04-22 06:06:57',
                'modified' => '2022-04-22 06:06:57',
            ],
            [
                'id' => '94',
                'user_id' => '5',
                'title' => 'tag test',
                'slug' => 'tag-test',
                'body' => 'タグ追加の操作テスト',
                'published' => '0',
                'created' => '2022-04-22 16:57:36',
                'modified' => '2022-04-22 16:59:28',
            ],
            [
                'id' => '171',
                'user_id' => '5',
                'title' => 'Authoraization test',
                'slug' => 'Authoraization-test',
                'body' => 'Authoraization test for testcase',
                'published' => '0',
                'created' => '2022-07-12 06:54:42',
                'modified' => '2022-07-12 06:54:42',
            ],
            [
                'id' => '173',
                'user_id' => '5',
                'title' => '大谷！！　頑張った　よくやった！！',
                'slug' => 'ootani-da-gu-wan-zhangtta',
                'body' => '６回１失点！　２桁勝利、20本塁打達成！　間近です',
                'published' => '0',
                'created' => '2022-07-14 04:38:56',
                'modified' => '2022-08-14 10:38:00',
            ],
            [
                'id' => '176',
                'user_id' => '5',
                'title' => '今日は記念すべき一日でした',
                'slug' => 'jin-riha-ji-niansubeki-yi-rideshita',
                'body' => '日本語入力は難しいです',
                'published' => '0',
                'created' => '2022-07-14 07:50:41',
                'modified' => '2022-07-14 07:50:41',
            ],
            [
                'id' => '177',
                'user_id' => '5',
                'title' => 'あなたのお家はどこですか？',
                'slug' => 'anatanoo-jiahadokodesuka',
                'body' => '名前を聞いてもいいですか？',
                'published' => '0',
                'created' => '2022-07-14 07:52:10',
                'modified' => '2022-07-14 07:52:10',
            ],
            [
                'id' => '179',
                'user_id' => '5',
                'title' => '山田の中の一本足の案山子',
                'slug' => 'shan-tianno-zhongno-yi-ben-zuno-an-shan-zi',
                'body' => '天気が良いのに蓑笠つけて、朝から晩まで唯たち通し、あーるけないのか山田の案山子',
                'published' => '0',
                'created' => '2022-07-14 07:58:41',
                'modified' => '2022-07-14 07:58:41',
            ],
            [
                'id' => '180',
                'user_id' => '5',
                'title' => '日本語バリデーション',
                'slug' => 'ri-ben-yubarideshon',
                'body' => '日本語バリデーションのテストです。add successfuly completed.
and edit successfuly completed too.
',
                'published' => '0',
                'created' => '2022-07-25 02:59:08',
                'modified' => '2022-07-25 03:01:16',
            ],
            [
                'id' => '181',
                'user_id' => '5',
                'title' => '夏休みがやってきました',
                'slug' => 'xia-xiumigayattekimashita',
                'body' => '天気予報では今年も暑い夏になりそうです',
                'published' => '0',
                'created' => '2022-07-25 03:04:42',
                'modified' => '2022-07-25 03:04:42',
            ],
            [
                'id' => '182',
                'user_id' => '5',
                'title' => '新しいフォームのテストです',
                'slug' => 'xinshiifomunotesutodesu',
                'body' => 'UIの操作性を確認しています',
                'published' => '0',
                'created' => '2022-07-31 04:06:56',
                'modified' => '2022-07-31 04:06:56',
            ],
            [
                'id' => '183',
                'user_id' => '7',
                'title' => '富美子の今日二番目の投稿です',
                'slug' => 'fu-mei-zino-jin-ri-er-fan-muno-tou-gaodesu',
                'body' => '暑い暑い暑い暑い！とても暑い夏になってきました、熱中症に気をつけましょう！',
                'published' => '0',
                'created' => '2022-07-31 05:13:44',
                'modified' => '2022-08-15 04:31:23',
            ],
            [
                'id' => '184',
                'user_id' => '5',
                'title' => 'Postロジックの動作検証',
                'slug' => 'Postrojikkuno-dong-zuo-jian-zheng',
                'body' => 'Article controller 内では、$this->Article->user_id　を参照。is Authorized fuction test for eidt method',
                'published' => '0',
                'created' => '2022-07-31 05:18:39',
                'modified' => '2022-08-14 07:38:17',
            ],
            [
                'id' => '185',
                'user_id' => '15',
                'title' => '庭の草取りしました!きれいになりました',
                'slug' => 'tingno-cao-qurishimashita',
                'body' => '今朝お父さんが庭の草取りをしました。春日井市の熱中症警戒警報が出たので昼前に終わりにしました。',
                'published' => '0',
                'created' => '2022-08-07 06:38:00',
                'modified' => '2022-08-09 11:59:02',
            ],
        ];

        $table = $this->table('articles');
        $table->insert($data)->save();
    }
}
